server:
  port: 9999

spring:
  thymeleaf:
    suffix: .html
    encoding: UTF-8
    cache: true
    mode: HTML
    prefix: classpath:/templates/
  devtools:
    restart:
      additional-paths: src/main/java
      exclude: static/layui/**,private/**
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456


#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
